name: finguruz
description: "FinGuruz - Personal Finance Management Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  http: ^1.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
